// Mock blog post data
// In a real application, this would be fetched from Contentlayer, a CMS, or API

export const allBlogPosts = [
  {
    title: 'The Ultimate Guide to Choosing Your First Motorcycle',
    slug: 'choosing-first-motorcycle',
    date: 'June 15, 2025',
    category: 'Buying Guides',
    tags: ['beginner', 'buying', 'first bike'],
    author: 'Mike Rider',
    excerpt: 'Find the perfect bike to start your two-wheeled journey with our comprehensive beginner\'s guide.',
    image: '/images/first-motorcycle.jpg',
    readingTime: '8 min read',
  },
  {
    title: 'Essential Motorcycle Maintenance You Can Do at Home',
    slug: 'essential-motorcycle-maintenance',
    date: 'June 10, 2025',
    category: 'Maintenance & DIY',
    tags: ['maintenance', 'DIY', 'tools'],
    author: 'Sarah Wrench',
    excerpt: 'Learn the basic maintenance tasks every rider should know to keep their bike running smoothly.',
    image: '/images/maintenance-diy.jpg',
    readingTime: '12 min read',
  },
  {
    title: 'Top 10 Motorcycle Helmets for 2025',
    slug: 'top-motorcycle-helmets-2025',
    date: 'June 5, 2025',
    category: 'Gear Reviews',
    tags: ['helmets', 'safety', 'gear', 'reviews'],
    author: 'David Gear',
    excerpt: 'Our experts tested dozens of helmets to find the best options for safety, comfort, and style.',
    image: '/images/helmets.jpg',
    readingTime: '10 min read',
  },
  {
    title: 'Riding Through the Rocky Mountains: A 7-Day Journey',
    slug: 'rocky-mountains-journey',
    date: 'May 28, 2025',
    category: 'Road Life',
    tags: ['travel', 'adventure', 'routes'],
    author: 'Lisa Traveler',
    excerpt: 'Follow along on an epic motorcycle adventure through some of America\'s most breathtaking landscapes.',
    image: '/images/rocky-mountains.jpg',
    readingTime: '15 min read',
  },
  {
    title: 'How to Master Slow-Speed Maneuvers',
    slug: 'master-slow-speed-maneuvers',
    date: 'May 22, 2025',
    category: 'Learn to Ride',
    tags: ['techniques', 'skills', 'riding'],
    author: 'Tom Instructor',
    excerpt: 'Improve your low-speed control with these expert techniques and practice exercises.',
    image: '/images/slow-speed.jpg',
    readingTime: '7 min read',
  },
  {
    title: 'The Rise of Electric Motorcycles: Are They Worth It?',
    slug: 'electric-motorcycles-worth-it',
    date: 'May 15, 2025',
    category: 'Blog',
    tags: ['electric', 'future', 'technology'],
    author: 'Emma Tech',
    excerpt: 'We explore the pros, cons, and future of electric motorcycles in an evolving industry.',
    image: '/images/electric-motorcycle.jpg',
    readingTime: '9 min read',
  },
  {
    title: 'Best Motorcycle Jackets for All Seasons',
    slug: 'best-motorcycle-jackets',
    date: 'May 10, 2025',
    category: 'Gear Reviews',
    tags: ['jackets', 'gear', 'safety', 'reviews'],
    author: 'Alex Style',
    excerpt: 'From summer mesh to winter waterproof, find the perfect jacket for your riding conditions.',
    image: '/images/motorcycle-jackets.jpg',
    readingTime: '11 min read',
  },
  {
    title: 'Understanding Motorcycle Engine Types',
    slug: 'motorcycle-engine-types',
    date: 'May 5, 2025',
    category: 'Buying Guides',
    tags: ['engines', 'technology', 'performance'],
    author: 'Chris Engineer',
    excerpt: 'From singles to V-twins to inline-fours, learn about the different engine configurations and their characteristics.',
    image: '/images/motorcycle-engines.jpg',
    readingTime: '13 min read',
  },
  {
    title: 'Route 66: The Ultimate Motorcycle Road Trip',
    slug: 'route-66-motorcycle-trip',
    date: 'April 28, 2025',
    category: 'Road Life',
    tags: ['travel', 'routes', 'USA', 'adventure'],
    author: 'Ryan Explorer',
    excerpt: 'Plan the perfect ride along America\'s historic highway with our detailed guide and tips.',
    image: '/images/route-66.jpg',
    readingTime: '14 min read',
  },
  {
    title: 'Motorcycle Tire Guide: Choosing the Right Rubber',
    slug: 'motorcycle-tire-guide',
    date: 'April 20, 2025',
    category: 'Maintenance & DIY',
    tags: ['tires', 'maintenance', 'safety'],
    author: 'Mark Mechanic',
    excerpt: 'Everything you need to know about motorcycle tires, from reading tire codes to selecting the best option for your riding style.',
    image: '/images/motorcycle-tires.jpg',
    readingTime: '10 min read',
  },
  {
    title: 'Women in Motorcycling: Breaking Barriers',
    slug: 'women-in-motorcycling',
    date: 'April 15, 2025',
    category: 'Blog',
    tags: ['women riders', 'community', 'inspiration'],
    author: 'Jessica Rider',
    excerpt: 'Celebrating the women who are changing the face of motorcycling and inspiring the next generation of female riders.',
    image: '/images/women-riders.jpg',
    readingTime: '8 min read',
  },
  {
    title: 'Cornering Techniques: The Perfect Line',
    slug: 'cornering-techniques',
    date: 'April 8, 2025',
    category: 'Learn to Ride',
    tags: ['techniques', 'skills', 'cornering', 'safety'],
    author: 'Sam Racer',
    excerpt: 'Master the art of cornering with these professional techniques that will make you faster and safer on the twisties.',
    image: '/images/cornering.jpg',
    readingTime: '9 min read',
  },
];
